

-- "Why do we use a left join? Because if we don't have a record in the 
-- views table, the entire contest will be dropped, regardless of 
-- whether it is presented in the submissions."

select * from
	(SELECT A.ID, A.HACKERID, A.NAME, 
		SUM(TOTAL_SUBMISSIONS) AS TOTAL_SUBMISSIONS, 
		SUM(TOTAL_ACCEPTED_SUBMISSIONS) AS TOTAL_ACCEPTED_SUBMISSIONS,
		SUM(TOTAL_VIEWS) AS TOTAL_VIEWS,
		SUM(TOTAL_UNIQUE_VIEWS) AS TOTAL_UNIQUE_VIEWS
	FROM CONTESTS AS A
	left join colleges as b
		on A.id = B.CONTESTID
	LEFT JOIN CHALLENGES AS C
		ON B.id = C.COLLEGEID
	LEFT JOIN (SELECT CHALLENGEID, SUM(TOTALVIEWS) AS TOTAL_VIEWS, 
					  SUM(TOTALUNIQUEVIEWS) AS TOTAL_UNIQUE_VIEWS
			   FROM Views
			   GROUP BY CHALLENGEID) AS D 
		ON C.id = D.CHALLENGEID 
	LEFT JOIN (SELECT CHALLENGEID, SUM(TOTALSUBMISSIONS) AS TOTAL_SUBMISSIONS, 
					  SUM(TOTALACCEPTEDSUBMISSIONS) AS TOTAL_ACCEPTED_SUBMISSIONS
			   FROM Submissions
			   GROUP BY CHALLENGEID) AS E
		ON C.id = E.CHALLENGEID
	GROUP BY A.ID, A.HACKERID, A.NAME) as temp
where (TOTAL_SUBMISSIONS + TOTAL_ACCEPTED_SUBMISSIONS + TOTAL_VIEWS + TOTAL_UNIQUE_VIEWS) > 0 
ORDER BY id;